// Lista de mensagens motivacionais
const mensagens = [
  "💪 Mesmo longe, sinto sua energia, meu amor. Você me impulsiona.",
  "❤️‍🔥 Cada dia que passa, meu desejo por você só aumenta, minha vida. Eu te amo.",
  "👑 Você é a força que eu não sabia que precisava, minha princesa.",
  "✨ Minha menina, sua coragem me faz admirá-la ainda mais.",
  "🔥 Meu tesão, a distância não apaga o fogo que sinto por você.",
  "😊 Você é a razão do meu sorriso, meu xuxu, mesmo quando estamos longe.",
  "🧘‍♂️ Sua presença, mesmo em pensamento, me acalma e me fortalece, meu amor.",
  "⚓ Pode contar comigo para o que der e vier, minha vida. Sou seu porto seguro.",
  "🧭 Minha princesa, estou aqui para te guiar em cada passo, mesmo de longe.",
  "💖 Você é a mulher que eu sempre quis, meu tesão. Eu te amo.",
  "😉 Nenhuma distância apaga o desejo de te ter, meu xuxu.",
  "🌸 Minha menina, você é a mais linda e a mais forte.",
  "🌟 Meu pedacinho do céu, saber que você existe me faz um homem melhor.",
  "❤️ Pequena mulher, minha mente e meu coração estão sempre com você.",
  "🌌 A distância é apenas um detalhe quando o amor é tão grande, meu amor.",
  "🌊 Eu te amo, minha vida, e a cada dia meu amor por você se aprofunda.",
  "🔒 Você está segura em meu coração, minha princesa, sempre.",
  "🗓️ Contar os dias para te ter em meus braços é minha rotina, meu tesão.",
  "🤩 Sua beleza me hipnotiza, meu xuxu, mesmo em fotos.",
  "👸 Minha menina, você é a rainha do meu mundo.",
  "✨ Meu pedacinho do céu, eu te desejo como nunca desejei ninguém.",
  "🤝 Pequena mulher, meu compromisso com você é inabalável.",
  "☀️ Seu brilho alcança onde eu estiver, meu amor.",
  "🗺️ Eu te amo, minha vida, e não há fronteiras para o que sinto.",
  "💍 Você é a mulher da minha vida, minha princesa, a única.",
  "🎶 Meu tesão, seu nome é a melodia que embala meus pensamentos.",
  "🦾 Minha menina, a sua força me inspira a ser mais forte também.",
  "🤗 Meu xuxu, sei que posso não estar ao seu lado, mas meu espírito te abraça.",
  "🙏 Quero cuidar de cada detalhe da sua vida, meu amor, mesmo de longe.",
  "💯 Você me faz sentir um homem completo, minha vida. Eu te amo.",
  "🚀 Sua determinação me fascina, minha princesa.",
  "💖 Minha menina, cada pensamento seu é um toque no meu coração.",
  "🌶️ Meu tesão, a saudade é o tempero que me faz te querer ainda mais.",
  "🏗️ Estou aqui para ser seu alicerce, meu xuxu, não importa a distância.",
  "🔥 Você é a paixão que incendeia minha alma, meu amor. Eu te amo.",
  "💡 Minha vida, sua inteligência me cativa.",
  "🛡️ Protejo você com a minha vida, minha princesa, mesmo que seja de longe.",
  "😔 Seu cheiro, sua pele, seu toque... tudo isso me faz falta, meu tesão.",
  "🎨 Minha menina, você é a arte mais linda que já vi.",
  "😄 Meu pedacinho do céu, sua alegria é a minha alegria.",
  "👊 Conte comigo para cada batalha, pequena mulher. Sou seu parceiro.",
  "💬 Eu te amo, meu amor, mais do que as palavras podem expressar.",
  "👂 Sua voz é meu acalento, minha vida, sempre.",
  "🏝️ Minha princesa, você é meu destino e meu paraíso.",
  "⏳ Meu tesão, a espera por você é a certeza de um amor que vale a pena.",
  "⭐ Minha menina, você é minha estrela guia.",
  "🔗 Meu xuxu, meu coração está conectado ao seu, não importa onde.",
  "💖 Eu te amo, meu amor, e a distância só prova a profundidade do meu sentimento.",
  "💎 Você é o meu maior tesouro, minha vida, e eu vou zelar por ele.",
  "💃 Sua ousadia me atrai de uma forma inexplicável, minha princesa.",
  "🔥 Meu tesão, mal posso esperar para sentir seu corpo junto ao meu.",
  "🌷 Minha menina, sua delicadeza me desarma.",
  "🦸‍♂️ Meu pedacinho do céu, sou seu protetor, mesmo com quilômetros de distância.",
  "😄 Pequena mulher, a sua felicidade é a minha prioridade.",
  "🔥 Você é a chama que me mantém aceso, meu amor. Eu te amo.",
  "💫 Minha vida, sua força interior me inspira a cada dia.",
  "👐 Meu toque te alcança em pensamento, minha princesa, sinta-o.",
  "⛰️ Meu xuxu, cada dia sem você é um desafio que enfrento por nosso amor.",
  "💪 Você é a minha motivação, meu tesão, para continuar lutando.",
  "🎁 Minha menina, você é o presente que a vida me deu.",
  "✨ Meu pedacinho do céu, sua presença, mesmo distante, me preenche.",
  "💑 Pequena mulher, sou completamente seu.",
  "🏃‍♂️ Eu te amo, meu amor, e farei de tudo para te ter perto logo.",
  "🧲 Sua beleza é um magnetismo, minha vida, que me puxa para você.",
  "🙏 Minha princesa, confie em mim, eu cuido de você.",
  "🌪️ Meu tesão, a vontade de te amar é avassaladora.",
  "💖 Minha menina, sua sensibilidade é um dom.",
  "♾️ Meu xuxu, estamos conectados por um laço que a distância não quebra.",
  "😥 Eu te amo, meu amor, e a saudade é prova de um amor imenso.",
  "😮 Você é a única mulher capaz de me tirar o fôlego, minha vida.",
  "⛽ Minha princesa, seu sorriso é meu combustível.",
  "😉 Meu tesão, eu te desejo de uma forma que você nem imagina.",
  "🥰 Minha menina, cada dia que passa me sinto mais seu.",
  "🕊️ Meu pedacinho do céu, você é a paz que eu busco.",
  "💯 Pequena mulher, meu respeito por você é infinito.",
  "💖 Você é a razão da minha existência, meu amor. Eu te amo.",
  "🤗 Minha vida, seu carinho me envolve mesmo de longe.",
  "🛡️ Minha princesa, te defendo de tudo e de todos, sempre.",
  "😈 Meu xuxu, sua ousadia me excita.",
  "👸 Minha menina, você é a rainha do meu mundo.",
  "💌 Meu pedacinho do céu, cada pensamento meu é um carinho para você.",
  "💪 Pequena mulher, eu te admiro por ser tão forte.",
  "🌪️ Eu te amo, meu amor, com a intensidade de um furacão.",
  "😵 Sua presença é meu vício, minha vida.",
  "🎁 Minha princesa, você é o meu presente mais valioso.",
  "🔥 Meu tesão, eu te quero em cada fibra do meu ser.",
  "🍬 Minha menina, sua doçura me conquista a cada instante.",
  "🦾 Meu xuxu, meu braço forte está sempre estendido para você.",
  "🏆 Eu te amo, meu amor, e a distância é apenas um desafio que vencemos juntos.",
  "💖 Você é a minha mulher, minha vida, e ninguém muda isso.",
  "🛡️ Minha princesa, te protejo de tudo, mesmo que não esteja ao seu lado.",
  "😍 Meu tesão, sua beleza me consome.",
  "🖼️ Minha menina, você é a obra de arte da minha vida.",
  "🏅 Meu pedacinho do céu, sua alegria é a minha maior recompensa.",
  "🦋 Pequena mulher, seu espírito livre me fascina.",
  "🌠 Eu te amo, meu amor, mais do que as estrelas no céu.",
  "💋 Sua sensualidade me prende, minha vida.",
  "💡 Minha princesa, você é a inspiração para os meus dias.",
  "😔 Meu xuxu, a saudade é um lembrete constante do quanto te amo.",
  "🏠 Minha menina, você é o meu lar, não importa onde eu esteja.",
  "💪🔥 Meu tesão, eu te desejo com toda a força do meu ser.",
  "💭 Meu pedacinho do céu, a vida com você é um sonho.",
  "🏗️ Pequena mulher, estou construindo um futuro para nós.",
  "🎵 Você é a melodia que embala meus sonhos, meu amor.",
  "💓 Eu te amo, minha vida, em cada batida do meu coração.",
  "🚀 Minha princesa, sua determinação me faz te admirar.",
  "🕰️ Meu xuxu, sinto sua falta a cada segundo, mas sei que vale a pena.",
  "🌅 Minha menina, você é a razão do meu amanhecer.",
  "🗺️ Meu tesão, seu corpo é um paraíso que anseio explorar.",
  "😊 Meu pedacinho do céu, cada vez que penso em você, um sorriso surge.",
  "⛰️ Pequena mulher, serei sua rocha inabalável.",
  "💪 Você me faz querer ser o melhor homem para você, meu amor.",
  "❤️‍🔥 Eu te amo, minha vida, com uma paixão que transcende a distância.",
  "✨ Minha princesa, seu olhar me desarma e me encanta.",
  "⏳ Meu xuxu, a espera só me deixa mais ansioso para te ter.",
  "🏆 Minha menina, você é a minha conquista mais valiosa.",
  "💋 Meu tesão, mal posso esperar para te beijar e te abraçar.",
  "🎤 Meu pedacinho do céu, sua voz é minha canção favorita.",
  "♾️ Pequena mulher, minha dedicação a você é eterna.",
  "💖 Você é a mulher que eu vou proteger e amar para sempre, meu amor.",
  "🔥 Eu te amo, minha vida, com uma intensidade que me consome.",
  "😮 Minha princesa, sua beleza me tira o fôlego.",
  "💫 Meu xuxu, você é a única que me faz sentir assim.",
  "🍯 Minha menina, sua doçura é minha fraqueza.",
  "💪 Meu tesão, o desejo de te ter em meus braços é constante.",
  "🌬️ Meu pedacinho do céu, sinto a sua presença, mesmo que esteja longe.",
  "🎯 Pequena mulher, você é a razão do meu foco.",
  "💑 Você é meu tudo, meu amor, e eu sou seu.",
  "💖 Eu te amo, minha vida, de um jeito que nunca amei.",
  "🧠 Minha princesa, sua inteligência me deixa ainda mais fascinado.",
  "💭 Meu xuxu, cada sonho que tenho é com você ao meu lado.",
  "🧭 Minha menina, você é a bússola que me guia.",
  "😉 Meu tesão, seu corpo é um convite irrecusável.",
  "😄 Meu pedacinho do céu, sua alegria é meu melhor som.",
  "⚔️ Pequena mulher, sou seu guerreiro, pronto para qualquer batalha.",
  "💡 Você é a minha luz, meu amor, em qualquer escuridão.",
  "🌌 Eu te amo, minha vida, mais do que o infinito.",
  "☀️ Minha princesa, sua presença ilumina qualquer ambiente.",
  "😔 Meu xuxu, a saudade é um sinal de que o que temos é real.",
  "💯 Minha menina, você é a perfeição em pessoa.",
  "✋ Meu tesão, mal posso esperar para te tocar e te sentir.",
  "🎵 Meu pedacinho do céu, você é a melodia da minha alma.",
  "👣 Pequena mulher, cada dia é um passo a mais para te ter perto.",
  "💪 Você é a força que me impulsiona, meu amor.",
  "🔥 Eu te amo, minha vida, com cada fibra do meu ser.",
  "🏆 Minha princesa, seu sorriso é minha maior vitória.",
  "🤗 Meu xuxu, a vontade de te abraçar é imensa.",
  "❤️ Minha menina, você é a razão do meu querer.",
  "🥶 Meu tesão, sua voz me arrepia a alma.",
  "😥 Meu pedacinho do céu, sinto sua falta em cada célula do meu corpo.",
  "🦁 Pequena mulher, sua coragem é algo que admiro profundamente.",
  "❤️‍🔥 Você é a essência do meu desejo, meu amor.",
  "⏳ Eu te amo, minha vida, e a cada segundo te quero mais.",
  "🧩 Minha princesa, você é a única que me completa.",
  "🕰️ Meu xuxu, eu anelo por cada momento ao seu lado.",
  "🦋 Minha menina, seu espírito livre me encanta.",
  "💯 Meu tesão, a distância é apenas um teste para o nosso amor.",
  "🏝️ Meu pedacinho do céu, você é meu refúgio em meio ao caos.",
  "🌟 Pequena mulher, seu brilho é inconfundível.",
  "💖 Eu te amo, meu amor, para além do tempo e do espaço.",
  "🌹 Minha vida, você é a flor mais rara do meu jardim.",
  "🛡️ Minha princesa, estarei sempre em sua defesa.",
  "🔥 Meu xuxu, o fogo da nossa paixão nunca se apaga.",
  "💖 Minha menina, sua alma é tão linda quanto seu sorriso.",
  "🔒 Meu tesão, meu coração é seu, e de mais ninguém.",
  "☀️ Meu pedacinho do céu, você é o sol que ilumina meus dias.",
  "👣 Pequena mulher, sigo seus passos em meus sonhos.",
  "💪 Você é a inspiração que me move, meu amor.",
  "❤️ Eu te amo, minha vida, com a força de um furacão.",
  "💫 Minha princesa, você é a estrela mais brilhante do meu céu.",
  "🥰 Meu xuxu, sua presença me faz querer ser mais.",
  "💎 Minha menina, você é meu maior tesouro.",
  "😉 Meu tesão, seu olhar diz tudo que preciso saber.",
  "🏠 Meu pedacinho do céu, com você, me sinto em casa.",
  "👑 Pequena mulher, você é a rainha que eu escolhi.",
  "💖 Eu te amo, meu amor, sem qualquer dúvida.",
  "🤝 Minha vida, nossa conexão é inquebrável.",
  "🔑 Minha princesa, você tem a chave do meu coração.",
  "🔥 Meu xuxu, a cada toque, meu desejo por você explode.",
  "🌷 Minha menina, sua delicadeza me fascina.",
  "🫂 Meu tesão, sinto seu abraço em cada pensamento.",
  "😌 Meu pedacinho do céu, você é minha paz.",
  "🌟 Pequena mulher, você é um milagre na minha vida.",
  "💪 Você me dá a força para enfrentar o mundo, meu amor.",
  "❤️‍🔥 Eu te amo, minha vida, e meu amor por você não tem fim.",
  "📈 Minha princesa, nosso amor só cresce, mesmo longe.",
  "🥵 Meu xuxu, você é meu tesão, minha paixão, meu tudo.",
  "💖 Minha menina, sua essência é pura luz.",
  "💯 Meu tesão, você é perfeita para mim.",
  "💡 Meu pedacinho do céu, sua mente é brilhante.",
  "🛡️ Pequena mulher, meu amor por você é um escudo.",
  "💖 Eu te amo, meu amor, em todas as suas formas.",
  "🎶 Minha vida, sua voz é minha canção favorita.",
  "🌹 Minha princesa, você me faz querer ser o melhor homem para você.",
  "😈 Meu xuxu, a distância só aguça o desejo de te ter.",
  "✨ Minha menina, sua aura me envolve.",
  "🌠 Meu tesão, você é meu desejo mais profundo.",
  "🌸 Meu pedacinho do céu, você floresce em meu coração.",
  "🌍 Pequena mulher, você é meu mundo.",
  "💪 Eu te amo, meu amor, com toda a minha força e virilidade.",
  "❤️ Eu te amo, minha vida, e a cada dia meu coração é mais seu.",
  "🧭 Minha princesa, você me guia nos momentos de incerteza.",
  "🔥 Meu xuxu, você é o fogo que acende a minha alma.",
  "💖 Minha menina, sua beleza é um presente divino.",
  "🔒 Meu tesão, sou seu, e você é minha.",
  "☀️ Meu pedacinho do céu, seu brilho nunca se apaga.",
  "👣 Pequena mulher, a distância nos ensina a amar mais intensamente.",
  "🏋️‍♂️ Meu amor, sua garra me inspira a ser um gigante.",
  "🌊 Eu te amo, minha vida, como as ondas do mar.",
  "👑 Minha princesa, você nasceu para brilhar ao meu lado.",
  "😉 Meu xuxu, cada lembrança sua me traz um sorriso e um desejo.",
  "💯 Minha menina, você é única e inigualável.",
  "🤩 Meu tesão, sou fascinado por cada curva sua.",
  "😌 Meu pedacinho do céu, com você, encontro a verdadeira paz.",
  "🚀 Pequena mulher, meu amor por você não tem limites.",
  "💖 Eu te amo, meu amor, de um jeito que nunca imaginei ser possível.",
  "🤝 Minha vida, nossa conexão é uma força da natureza.",
  "🔑 Minha princesa, você abriu as portas do meu coração.",
  "🔥 Meu xuxu, a paixão por você arde em mim.",
  "🌷 Minha menina, sua alma é tão bela quanto uma flor.",
  "🤗 Meu tesão, sinto seu corpo junto ao meu, mesmo a distância.",
  "🌟 Meu pedacinho do céu, você é meu porto seguro.",
  "💪 Pequena mulher, sua força me faz te amar ainda mais.",
  "💖 Eu te amo, meu amor, incondicionalmente e para sempre.",
  "🎶 Minha vida, sua risada é a trilha sonora da minha felicidade.",
  "🛡️ Minha princesa, eu serei seu guardião eterno.",
  "🥵 Meu xuxu, você é o desejo que me consome.",
  "✨ Minha menina, sua aura é mágica, me envolvendo e me prendendo a você.",
  "🌠 Meu tesão, você é o sonho que se tornou realidade.",
  "🌸 Meu pedacinho do céu, você é a primavera na minha vida.",
  "🌍 Pequena mulher, meu amor por você não tem fronteiras.",
  "💪 Eu te amo, meu amor, com a alma de um guerreiro e o coração de um amante.",
  "❤️ Eu te amo, minha vida, e minha dedicação a você é absoluta.",
  "🧭 Minha princesa, você me guia para os melhores caminhos.",
  "🔥 Meu xuxu, seu calor me aquece mesmo longe.",
  "💖 Minha menina, sua beleza é atemporal e marcante.",
  "🔒 Meu tesão, você é minha e eu sou seu, para sempre.",
  "☀️ Meu pedacinho do céu, você é a luz que afasta minhas sombras.",
  "👣 Pequena mulher, a distância só me faz te querer mais perto.",
  "🏋️‍♂️ Meu amor, sua tenacidade me inspira a ser indomável.",
  "🌊 Eu te amo, minha vida, com a profundidade do oceano.",
  "👑 Minha princesa, você é a única que merece meu trono.",
  "😉 Meu xuxu, sua ousadia me excita e me fascina.",
  "💯 Minha menina, você é a obra-prima da minha vida.",
  "🤩 Meu tesão, sua presença é um deleite para os meus sentidos.",
  "😌 Meu pedacinho do céu, você é o meu refúgio e minha segurança.",
  "🚀 Pequena mulher, meu amor por você voa alto, sem medo.",
  "💖 Eu te amo, meu amor, em cada batida do meu coração.",
  "🤝 Minha vida, nosso vínculo é inquebrável.",
  "🔑 Minha princesa, você é a chave para a minha felicidade plena.",
  "🦾 Meu amor, sinto sua falta, mas sei que nosso amor é mais forte que a distância.",
  "❤️‍🔥 Minha vida, meu desejo por você é um fogo que me consome. Eu te amo.",
  "👑 Minha princesa, você é a mulher dos meus sonhos, a que me completa.",
  "✨ Minha menina, sua resiliência me faz te admirar cada vez mais.",
  "🔥 Meu tesão, a cada pensamento em você, meu corpo se acende.",
  "😊 Meu xuxu, seu sorriso é o meu raio de sol em dias nublados.",
  "🧘‍♂️ Meu amor, a certeza do seu amor me traz uma paz que não tem preço.",
  "⚓ Minha vida, eu sou seu e você é minha, não importa a distância.",
  "🧭 Minha princesa, estarei aqui para te guiar em todas as suas escolhas.",
  "💖 Meu tesão, eu te amo com uma intensidade que transborda.",
  "😉 Meu xuxu, você é o desejo que me move, que me faz querer mais.",
  "🌸 Minha menina, sua beleza é única, e eu sou um homem de sorte.",
  "🌟 Meu pedacinho do céu, você me faz acreditar no amor verdadeiro.",
  "❤️ Pequena mulher, meu coração bate no ritmo do seu, mesmo longe.",
  "🌌 Meu amor, nossa conexão é cósmica, transcende qualquer barreira.",
  "🌊 Eu te amo, minha vida, como o oceano ama a lua.",
  "🔒 Minha princesa, meu coração é seu santuário, e você está segura nele.",
  "🗓️ Meu tesão, conto os segundos para te ter aqui, nos meus braços.",
  "🤩 Meu xuxu, sua presença, mesmo que virtual, me eletriza.",
  "👸 Minha menina, você comanda o meu mundo, e eu amo isso.",
  "✨ Meu pedacinho do céu, sua luz é um farol na minha vida.",
  "🤝 Pequena mulher, nosso compromisso é selado, e eu o honrarei.",
  "☀️ Meu amor, você é a estrela mais brilhante no meu céu.",
  "🗺️ Eu te amo, minha vida, e juntos conquistaremos o mundo.",
  "💍 Minha princesa, você é a joia mais rara, a que eu guardo com ciúme.",
  "🎶 Meu tesão, sua voz é a sinfonia que acalma minha alma agitada.",
  "🦾 Minha menina, sua determinação me faz um homem ainda mais forte.",
  "🤗 Meu xuxu, meu pensamento te abraça e te aperta com força.",
  "🙏 Meu amor, cada oração minha é para te ver feliz e realizada.",
  "💯 Minha vida, você me completa de uma forma que eu nunca imaginei. Eu te amo.",
  "🚀 Minha princesa, você me impulsiona a ir além, a ser mais.",
  "💖 Minha menina, cada pulsar do meu coração é um lembrete do meu amor por você.",
  "🌶️ Meu tesão, a saudade é um fogo que me lembra o quanto te desejo.",
  "🏗️ Meu xuxu, construiremos um império juntos, não importa a distância.",
  "🔥 Meu amor, você é a paixão que incendeia cada célula do meu corpo. Eu te amo.",
  "💡 Minha vida, sua mente é um universo a ser explorado, e eu adoro isso.",
  "🛡️ Minha princesa, eu serei sua muralha, seu escudo, seu protetor.",
  "😔 Meu tesão, a saudade é bruta, mas o amor é mais forte.",
  "🎨 Minha menina, você é a inspiração por trás das minhas melhores ideias.",
  "😄 Meu pedacinho do céu, sua alegria é a minha maior inspiração.",
  "👊 Pequena mulher, sou seu aliado em todas as batalhas da vida.",
  "💬 Meu amor, as palavras são poucas para descrever o que sinto por você.",
  "👂 Minha vida, sua voz é música para meus ouvidos, a melhor canção.",
  "🏝️ Minha princesa, com você, a vida é um paraíso a ser desfrutado.",
  "⏳ Meu tesão, a espera só aumenta o valor do nosso reencontro.",
  "⭐ Minha menina, você é a estrela que me guia na escuridão.",
  "🔗 Meu xuxu, nosso laço é inquebrável, forte como aço.",
  "💖 Meu amor, meu amor por você é um abismo sem fim, eu te amo.",
  "💎 Minha vida, você é meu tesouro mais precioso, e eu te guardo a sete chaves.",
  "💃 Minha princesa, sua ousadia e sua garra me deixam louco por você.",
  "💪 Meu tesão, sinto que nasci para te proteger e te amar eternamente.",
  "👑 Minha menina, você é a dona do meu destino, minha rainha.",
  "☀️ Meu pedacinho do céu, seu brilho é a luz que ilumina meus passos.",
  "💖 Pequena mulher, você me faz um homem mais forte e completo a cada dia. Eu te amo.",
  "🔐 Meu amor, meu coração está trancado, e só você tem a chave.",
  "🌌 Minha vida, nosso amor é um universo vasto e infinito. Eu te amo.",
  "🌟 Minha princesa, você é a estrela mais brilhante do meu céu particular.",
  "🔥 Meu xuxu, a chama da nossa paixão nunca se apagará, pode crer.",
  "😊 Meu tesão, seu sorriso é a minha maior recompensa e minha fraqueza.",
  "⚓ Minha menina, sou seu porto seguro, seu rochedo, sua fortaleza.",
  "🧭 Meu pedacinho do céu, minha direção é sempre você, meu guia.",
  "💖 Pequena mulher, eu te amo com a força de mil exércitos e a doçura de um beijo.",
  "⚡ Meu amor, você é a energia que me impulsiona, a faísca da minha vida.",
  "📈 Minha vida, nosso amor só cresce, desafiando tempo e distância.",
  "🫂 Minha princesa, sinto seus abraços, mesmo que em meus pensamentos, apertando a alma.",
  "🥵 Meu tesão, a cada segundo longe, o desejo por você me consome. Você é minha.",
  "✨ Minha menina, sua essência é mágica, pura e me encanta profundamente.",
  "🚀 Meu pedacinho do céu, você me leva a alturas que nunca imaginei alcançar. Eu te amo.",
  "🤝 Pequena mulher, a parceria com você é a base da minha existência. Contigo, sempre.",
  "💪 Meu amor, te prometo proteção, cuidado e um amor inabalável para sempre.",
  "💍 Minha vida, você é a escolha certa, a única mulher para mim. Eu te amo.",
  "🎶 Minha princesa, sua voz é a melodia que acalma a tempestade em mim.",
  "🌌 Meu xuxu, o desejo de te ter perto é um universo que se expande a cada dia.",
  "🌠 Meu tesão, você é o meu sonho mais vívido e a minha realidade mais ardente.",
  "🌸 Minha menina, você floresce em meu coração, mesmo a distância, me cobrindo de amor.",
  "🌍 Meu pedacinho do céu, meu mundo é você, e eu te protejo nele.",
  "💖 Pequena mulher, meu amor por você é um escudo impenetrável. Eu te amo.",
  "⚔️ Meu amor, serei seu defensor em qualquer campo de batalha que a vida apresentar.",
  "🌊 Minha vida, a profundidade do meu amor por você é como o oceano, sem fim. Eu te amo.",
  "👑 Minha princesa, sua realeza é evidente em sua força e em sua alma.",
  "😉 Meu xuxu, seu jeito me instiga e me faz te querer ainda mais a cada instante.",
  "💯 Minha menina, a perfeição existe, e ela se manifesta em você.",
  "🤩 Meu tesão, sua beleza me rouba o fôlego, me deixando sem ar de paixão.",
  "😌 Meu pedacinho do céu, sua presença, mesmo longe, me traz a paz que eu busco.",
  "🚀 Pequena mulher, meu amor por você não conhece limites nem gravidade.",
  "💖 Meu amor, eu te amo com a verdade mais pura que um homem pode sentir.",
  "🤝 Minha vida, nossa união, mesmo que distante, é forte e inquebrável.",
  "🔑 Minha princesa, você abriu as portas do meu coração e eu te dou a chave da minha vida.",
  "🔥 Meu xuxu, a paixão por você é um fogo que consome cada fibra do meu ser.",
  "🌷 Minha menina, sua delicadeza me envolve e me encanta, me deixando cativado.",
  "🤗 Meu tesão, a saudade é um abraço apertado do meu coração no seu.",
  "🌟 Meu pedacinho do céu, você é a estrela que me guia, me mostrando o caminho.",
  "💪 Pequena mulher, sua força me dá a coragem de enfrentar qualquer coisa.",
  "💖 Eu te amo, meu amor, em cada suspiro, em cada batida do meu coração.",
  "🎶 Minha vida, sua risada é a trilha sonora mais bonita que eu já ouvi.",
  "🛡️ Minha princesa, eu serei seu guardião, sua proteção contra o mundo.",
  "🥵 Meu xuxu, você é o desejo que me impulsiona, a sede que me consome.",
  "✨ Minha menina, sua aura é mágica, me envolvendo e me prendendo a você.",
  "🌠 Meu tesão, você é o sonho que eu persigo e a realidade que eu anseio viver.",
  "🌸 Meu pedacinho do céu, você floresce em meu jardim secreto, sempre linda.",
  "🌍 Pequena mulher, meu mundo é você, e eu te protejo nele.",
  "💪 Eu te amo, meu amor, com a alma de um guerreiro e a devoção de um amante.",
  "❤️ Eu te amo, minha vida, e minha dedicação a você é absoluta e eterna.",
  "🧭 Minha princesa, você me guia nos labirintos da vida, me mostrando a saída.",
  "🔥 Meu xuxu, seu calor me aquece mesmo nas noites mais frias da distância.",
  "💖 Minha menina, sua beleza é atemporal e marcante.",
  "🔒 Meu tesão, você é minha e eu sou seu, para sempre.",
  "☀️ Meu pedacinho do céu, você é a luz que afasta minhas sombras e traz a luz.",
  "👣 Pequena mulher, a distância apenas aprofunda a intensidade do meu amor por você.",
  "🏋️‍♂️ Meu amor, sua tenacidade me inspira a ser indomável, um homem à sua altura.",
  "🌊 Eu te amo, minha vida, com a profundidade de um oceano sem fim.",
  "👑 Minha princesa, você é a única que merece meu trono e meu reino.",
  "😉 Meu xuxu, sua ousadia e sua confiança são um convite irrecusável.",
  "💯 Minha menina, você é a obra-prima da minha vida, minha joia mais rara.",
  "🤩 Meu tesão, sua presença é um deleite para os meus sentidos, mesmo que virtual.",
  "😌 Meu pedacinho do céu, você é o meu refúgio seguro e a minha paz interior.",
  "🚀 Pequena mulher, meu amor por você voa alto, sem medo de cair.",
  "💖 Eu te amo, meu amor, em cada batida do meu coração, para sempre.",
  "🤝 Minha vida, nosso vínculo é inquebrável, forte como a rocha mais sólida.",
  "🔑 Minha princesa, você é a chave para a minha felicidade plena e absoluta.",
  "❤️‍🔥 Meu amor, cada segundo com você é uma eternidade que eu quero viver. Eu te amo.",
  "🌌 Minha vida, seu encanto é um mistério que eu adoro desvendar. Eu te amo.",
  "🌟 Minha princesa, sua presença, mesmo distante, me acende por dentro.",
  "🔥 Meu xuxu, o desejo por você é uma chama que nunca se apaga em mim.",
  "😊 Meu tesão, seu sorriso é o meu maior combustível para seguir em frente.",
  "⚓ Minha menina, sou sua âncora, seu porto seguro em qualquer mar bravo.",
  "🧭 Meu pedacinho do céu, você é a bússola que orienta todos os meus passos.",
  "💖 Pequena mulher, eu te amo com a força da gravidade que me puxa para você.",
  "⚡ Meu amor, você é a tempestade que me agita e a calmaria que me acalma. Eu te amo.",
  "📈 Minha vida, a cada dia que passa, sinto que nosso amor só se aprofunda.",
  "🫂 Minha princesa, mesmo sem toque, sinto a maciez da sua pele em meus pensamentos.",
  "🥵 Meu tesão, o desejo de te ter em meus braços me faz delirar de paixão.",
  "✨ Minha menina, sua alma é um tesouro, e eu sou um guardião zeloso.",
  "🚀 Meu pedacinho do céu, você me inspira a voar mais alto, a sonhar mais longe. Eu te amo.",
  "🤝 Pequena mulher, nossa conexão é uma promessa que eu vou cumprir em cada detalhe.",
  "💪 Meu amor, a distância não diminui um pingo da minha virilidade por você.",
  "💍 Minha vida, você é a única joia que eu quero lapidar e proteger para sempre. Eu te amo.",
  "🎶 Minha princesa, sua voz é a melodia que me faz dançar a vida.",
  "🌌 Meu xuxu, a cada estrela que vejo, lembro da luz que você traz para a minha vida.",
  "🌠 Meu tesão, você é o meu desejo mais profundo, a minha obsessão mais pura.",
  "🌸 Minha menina, você é a flor mais rara, e eu serei seu jardineiro fiel.",
  "🌍 Meu pedacinho do céu, meu universo gira em torno da sua existência. Eu te amo.",
  "💖 Pequena mulher, meu amor por você é a armadura que me torna invencível. Eu te amo.",
  "⚔️ Meu amor, estarei na frente de qualquer batalha para te proteger, sempre.",
  "🌊 Minha vida, meu amor por você é profundo como o abismo e vasto como o oceano.",
  "👑 Minha princesa, você é a realeza que governa meu coração e minha alma.",
  "😉 Meu xuxu, seu jeito sedutor me prende, me amarra a você de um jeito bom.",
  "💯 Minha menina, você é a perfeição em todos os sentidos, a minha obra-prima.",
  "🤩 Meu tesão, sua beleza é um convite irrecusável para uma paixão sem limites.",
  "😌 Meu pedacinho do céu, em seus braços, mesmo que imaginários, encontro a paz.",
  "🚀 Pequena mulher, meu amor por você é um lançamento, sempre para frente e para o alto.",
  "💖 Meu amor, eu te amo com a força de um leão e a ternura de um abraço. Eu te amo."
];

// Escolhe uma aleatória ao carregar a página
window.addEventListener('DOMContentLoaded', () => {
  const mensagemElemento = document.getElementById('mensagem');
  const aleatoria = mensagens[Math.floor(Math.random() * mensagens.length)];
  mensagemElemento.textContent = aleatoria;
});
